### ISSUE TITLE
get.yourpass.eu only provides a qr code and makes it less friendly to import into the app

### ISSUE THREAD

**Issue by zubozrout** [patrickjane/ut-passes#5]
Hi,
this site: get.yourpass.eu only provides a QR code to import to Android/iOS version of a "Yourwallet" app.

An example can be found here: https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936
One can also use this link to get the file: https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936?format=pkpass
but it is not obvious to random site visitors.

It would be very nice to be able to import urls or QR codes as well to then auto-download the .pkpass file and saving it into the app just as with direct file imports. For QR code functionality allowing Tagger to share the scanned code content via the content hub should more than enough. Or alternatively this could be implemented right into the app itself, similar to how the Corona App does it: https://gitlab.com/arnef/coronaapp

Thank you for your thoughts on this.

**Comment by patrickjane** [comment]
Okay so scanning QR codes from within the app is not an issue, I have implemented this in my ut-scooter app already. However, taking a deeper look at this, it does not seem to be that easy.

The problem is, that once you scan the code, you will just get to the same URL again.

E.g.

1) You open https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936 in the browser
2) You click "save to iphone"
3) You scan the QR code, which results in the URL https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936
4) So now you have the same URL on your phone, but you don't have any option to download the pass as .pkfile, since that website is attempting to auto-detect your device, and will present you with an android app handler link instead of a link to the .pkpass file.

Of course, I could just add "?format=pkpass" to the URL in step 3), however this would mean that I am adding specific support for a single given website into the app, which I want to avoid. I want the app to be of general purpose, without implementing website specifics. So as it seems, unless I missed something, https://get.yourpass.eu is not offering a way to download the .pkpass file, unless you're on iPhone.

**Comment by zubozrout** [comment]
Thank you for your reply and for having a look @patrickjane!
I was expecting the QR code to be giving direct links to the pkpass file, but unfortunately I didn't check it closely :(.

And yes, I agree. Having individual site tweaks in the app is not a way to go. So I would say this is good to be closed.
Let this ticket be a how-to for others if they want to import content from that site over to your app :).

**Comment by zubozrout** [comment]
Btw, it has been brought to my attention that on mobile, the site shows a button with a link like this:
```
intent://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936?format=pkpass#Intent;scheme=yourwallet;package=eu.yourpass.wallet;S.market_referrer=https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936?format=pkpass;end
```
Which could likely be catched by url dispatcher:
https://docs.ubports.com/en/latest/appdev/guides/importing-CH-urldispatcher.html
and then direct GET request on `https://get.yourpass.eu/09534050-f392-4758-a9ae-356e927ee936?format=pkpass...` does work. 

Though:

1. I haven't tried an url starting with `intent://`, so not sure what Morph would say to that
2. It is still service specific, but I guess much less problematic as the url list can be create without too much trouble.
3. But likely even the url change from `intent://...` to `https://...` could be service specific, and that might be an issue. But I have nothing to compare this to.

What would you think about that @patrickjane? Thank you!
